# Generated by Django 5.0.4 on 2024-04-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_urecipe_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urecipe",
            name="recipe_image",
            field=models.ImageField(blank=True, null=True, upload_to="pics"),
        ),
    ]
